### ISSUE TITLE
V0.8 support 

### ISSUE THREAD

**Issue by binyaminyblatt** [Suwayomi/tachidesk-paperback-ext#3]
I have the new beta version version 0.8 and every time I try to use this extension it crashes the entire app

**Comment by AlexZorzi** [comment]
Sadly i don't have the device to maintain this repo anymore, we are searching for maintainers.

**Comment by binyaminyblatt** [comment]
Let me talk to the people on discord who maintain most of the other repositories maybe I can get somebody to pick it up

**Comment by AlexZorzi** [comment]
Closed by #4
